[package]
name = "fate-test-game"
version = "0.1.0"
authors = ["Yoan Lecoq <yoanlecoq.io@gmail.com>"]

[dependencies]
fate = { path = "../fate" }
log = "~0.4.2"
env_logger = "0.5.0-rc.1"
backtrace = "~0.3.5"

