cargo-features = ["profile-overrides"]

[workspace]
members = [
    "lab",
    "math",
    "font",
    "img",
    "gx",
    "main-loop",
    "fate",
    "game",
]

[profile.dev.overrides.image]
opt-level = 3
[profile.dev.overrides.image."*"]
opt-level = 3
