[package]
name = "fate-img"
description = "An API layer over image loading/saving/utility libraries"
version = "0.1.0"
authors = ["Yoan Lecoq <yoanlecoq.io@gmail.com>"]

[dependencies]
imgref = "~1.3.5"
image = "~0.19.0" 
stb_image = "~0.2.2"
vek = "~0.9.0"